/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package REST;

import spark.Spark;


public class App {

    public static void main(String[] args) {
        //Spark.get("/users/0/welcome", (req, res) -> {return "Hallo Ueli";});
        Spark.get("/users/1/welcome", (req, res) -> {return "DevOps Project Week 3!";});
    }
}